version: "3.3"
services:
 asir_bind9:
   image: ubuntu
   networks:
      - br02
   ports:
     - 53:53
   volumes:
     - conf:/etc/bind
 asir_cliente:
   image: ubuntu
   networks:
      - br02
   stdin_open: true  # docker run -i
   tty: true         # docker run -t
   dns:
     - 172.19.0.3 # el contenedor dns server
volumes:
 conf:
   external: true

networks:
  br02:
    external: true # tenemos que tenerlo crado previamente